name: test
on:
  push:
    branches:
    - main

env:
  FIRST_NAME: Mona
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            echo "env_var:$FIRST_NAME" >> /tmp/env-teste.log
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
          args: "-tt -vvv"
          